ci: add xml reporting(experimental)

diff --git a/.github/workflows/tests-integration.yaml b/.github/workflows/tests-integration.yaml
--- a/.github/workflows/tests-integration.yaml
+++ b/.github/workflows/tests-integration.yaml
@@ -15,6 +15,8 @@ permissions:
     id-token: write
     contents: write
     pull-requests: write
+    actions: write
+    checks: write 
 
 env:
     TF_VAR_observe_url: ${{secrets.OBSERVE_URL}}
@@ -23,9 +25,8 @@ env:
 
 
 jobs:
-
   helm-charts-agent-integration-tests:
-    name: helm-charts-agent-integration-tests-${{ matrix.namespace }}-${{ matrix.values }}
+    name: ns-${{ matrix.namespace }}+values-${{ matrix.values }}
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
@@ -41,7 +42,7 @@ jobs:
               namespace: not-observe
     defaults:
         run:
-            working-directory: integration #Terrafrom commands and tests are ran from integration directory
+            working-directory: integration #Terraform commands and tests are ran from integration directory
     steps:
         - name: Checkout code
           uses: actions/checkout@v4
@@ -59,13 +60,20 @@ jobs:
           uses: actions/setup-python@v5
           with:
             python-version: '3.10'
+        
+        - uses: actions/setup-node@v4
+          with:
+            node-version: 18
+        - run: |
+            npm init -y
+            npm install --legacy-peer-deps
 
         - run: pip install -r scripts/requirements.txt
 
         - name: Setup Terraform
           uses: hashicorp/setup-terraform@v3
-          with:
-            terraform_version: 1.9.5
+          with: #Use alpha version which has experimental Junit feature. 
+            terraform_version: "1.10.0-alpha20240918" 
 
         - name: Terraform Init
           id: init
@@ -78,4 +86,19 @@ jobs:
         - name: Terraform Test
           id: test
           run: |
-            terraform test -verbose
+            terraform test -verbose -junit-xml=results-ns-${{ matrix.namespace }}+values-${{ matrix.values }}.xml            
+        
+        # - name: Upload Test Results
+        #   uses: actions/upload-artifact@v4
+        #   if: success() || failure()
+        #   with:
+        #     name: results-ns-${{ matrix.namespace }}+values-${{ matrix.values }}
+        #     path: ${{ github.workspace }}/integration/*.xml         
+
+        - name: Run CTRF annotations ####TODO Currently this doesn't work properly as the conversion from xml to crtf is not proper on certain xml files
+          run: |
+            cat results-ns-${{ matrix.namespace }}+values-${{ matrix.values }}.xml
+            npx junit-to-ctrf results-ns-${{ matrix.namespace }}+values-${{ matrix.values }}.xml
+            cat ctrf/ctrf-report.json
+            npx github-actions-ctrf ai ctrf/ctrf-report.json            
+          if: always()
